
version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: mySQL
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'Ferrari1993.'
    volumes:
      - /Users/danielullauri93/Documents/MYSQL:/var/lib/mysql
